Кошкелян Тигран Задание 1
sopilnyak/dotnet-course pull request #11
Opened 2022-03-10 21:10 UTC by TIGRAN02

2022-05-07 12:51 UTC, sopilnyak requested changes
Предварительная оценка (без исправлений): 8 баллов из 10.

2022-05-07 12:51 UTC, sopilnyak commented on 02-oop/Program.cs
> +    public SorterLogConsole() : base()
Довольно странная архитектура классов про логирование. Как логирование связано с сортировкой? А если мы захотим использовать классы, связанные с логированием, не только для сортировки?
Гораздо лучше сделать интерфейс ILogger и передавать его в конструктор BasicSorter. А реализации у него будут ConsoleLogger и FileLogger - в консоль и в файл соответственно.
И тогда в классе BasicSorter можно будет звать метод интерфейса ILogger.

2022-05-07 12:51 UTC, sopilnyak commented on 02-oop/Program.cs
> +}
Еще хорошо бы добавить Main с примером использования

2022-05-07 16:05 UTC, TIGRAN02 commented on 02-oop/Program.cs
> +    public SorterLogConsole() : base()
Исправил

2022-05-07 16:05 UTC, TIGRAN02 commented on 02-oop/Program.cs
> +}
Добавил

2022-05-07 16:05 UTC, TIGRAN02 commented on 02-oop/Program.cs
> +public interface ISorter<T> where T : IComparable
Исправил

2022-05-08 11:11 UTC, sopilnyak commented on 02-oop/Program.cs
> +    public SorterLogConsole() : base()
Всё правильно, только StreamWriter нужно закрывать (для этого можно FileLogger отнаследовать от IDisposable, реализовать Dispose с `_writer.Dispose()` и при создании запихать его под using).

2022-05-08 11:12 UTC, sopilnyak commented
Оценка с исправлениями: 10.

2022-05-08 11:12 UTC, closed without merging