Rusetskiy Dmitriy 1 task
sopilnyak/dotnet-course pull request #2
Opened 2022-03-10 04:40 UTC by DmitriRuset

2022-04-24 19:57 UTC, sopilnyak requested changes
Предварительная оценка (без исправлений): 8 баллов из 10

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +    public interface ILogger {
Принято каждый класс (а тем более неймспейс) держать в отдельном файле

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +        public ConsoleLogger() { }
Пустой конструктор определять не обязательно

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +    interface ISorter<T> {
Для интерфейсов тоже нужно указывать модификаторы (public, internal и т.п.)

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +        private int Partition(T[] arr, int start_idx, int end_idx) {
По Microsoft C# Coding Convensions (общепринятому кодстайлу) надо параметры называть `startIdx` и `endIdx`.

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +            throw new ArgumentException("Сравнивание несравнимых типов");
Ошибка вроде не совсем про сравнение несравнимых типов

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +        private logger.ILogger _logger;
По кодстайлу сначала надо объявлять поля и свойства, а потом методы, чтобы не приходилось листать в конец, чтобы понять, что лежит в классе

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +        private const int _limit_on_items = 20;
По кодстайлу все константы (даже приватные) с большой буквы: `LimitOnItems`.

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +        public T[] arr { get; }
По кодстайлу свойства с большой буквы

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +        private logger.ILogger _logger;
Неймспейс не надо указывать, есть же using

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +                BubbleSort<T> bubbleSort = new BubbleSort<T>();
Можно var использовать, чтобы не дублировать тип

2022-04-24 19:57 UTC, sopilnyak commented on 02-oop/Program.cs
> +            if (watch.Elapsed.Ticks <= 10000) {
Тернарный оператор вместо if-else подойдет гораздо лучше

2022-05-15 15:07 UTC, DmitriRuset commented on 02-oop/Program.cs
> +    public interface ILogger {
Учел. Добавил 2 файла: loggers.cs и sorters.cs

2022-05-15 15:07 UTC, DmitriRuset commented on 02-oop/Program.cs
> +        public ConsoleLogger() { }
Убрал пустые конструкторы.

2022-05-15 15:07 UTC, DmitriRuset commented on 02-oop/Program.cs
> +    interface ISorter<T> {
Указал.

2022-05-15 15:07 UTC, DmitriRuset commented on 02-oop/Program.cs
> +        private int Partition(T[] arr, int start_idx, int end_idx) {
Поменял snake_case на camelCase

2022-05-15 15:08 UTC, DmitriRuset commented on 02-oop/Program.cs
> +            throw new ArgumentException("Сравнивание несравнимых типов");
Переделал сообщение.

2022-05-17 21:05 UTC, sopilnyak commented
Пропустил 1 коммент про то, что поля и свойства обычно идут перед методами.
Но это не так важно. Поднимаю до 10.

2022-05-17 21:05 UTC, closed without merging