Кошкелян Тигран Задание 3
sopilnyak/dotnet-course pull request #27
Opened 2022-04-29 23:51 UTC by TIGRAN02

2022-05-15 10:38 UTC, sopilnyak requested changes
Предварительная оценка (без исправлений): 9 баллов из 10.

2022-05-15 10:38 UTC, sopilnyak commented on 06-testing/Solution/BatchIterator.cs
> +            yield return _data.Skip(start).Take(_batchSize);
Это не слишком оптимально, т.к. в общем случае (если _data не IList<T>) мы каждый раз ходим за линию с начала массива

2022-05-15 10:38 UTC, sopilnyak commented on 06-testing/Solution/BatchIteratorTests.cs
> +    [TestCase(new [] {1, 2, 3, 4}, 2)]
Можно еще проверить невалидный batchSize (= 0 или < 0), должно кидаться адекватное исключение.

2022-05-15 10:38 UTC, sopilnyak commented on 06-testing/Solution/Document.cs
> +        var random = new Random();
Дефолтный seed тоже случайный, так что для повторяемости надо зафиксировать seed.

2022-05-15 16:15 UTC, TIGRAN02 commented on 06-testing/Solution/BatchIterator.cs
> +            yield return _data.Skip(start).Take(_batchSize);
Исправил

2022-05-15 16:15 UTC, TIGRAN02 commented on 06-testing/Solution/BatchIteratorTests.cs
> +    [TestCase(new [] {1, 2, 3, 4}, 2)]
Испрааил и погрустил, что в C# нет throws как в джаве:(

2022-05-15 16:17 UTC, TIGRAN02 commented on 06-testing/Solution/Document.cs
> +        var random = new Random();
Добавил Seed

2022-05-17 20:34 UTC, sopilnyak commented on 06-testing/Solution/BatchIterator.cs
> +            yield return _data.Skip(start).Take(_batchSize);
Ну это чит какой-то с листом, ну да ладно.
Вообще говоря не всегда лишний раз преобразовывать в List - это оптимальная операция. Представь если у нас в этом IEnumerable лежат записи в базе данных и читать их все в память не то что бы дешево.
Гораздо лучше было бы 1 раз пройтись по IEnumerable и возвращать по одному батчу, а пользователь класса уже пусть что хочет с ними делает.

2022-05-17 20:38 UTC, sopilnyak commented on 06-testing/Solution/BatchIteratorTests.cs
> +    [TestCase(new [] {1, 2, 3, 4}, 2)]
Да, в C# это обычно в документации к методу прописывается: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags
Тег `<exception>` как раз про это.

2022-05-17 20:38 UTC, sopilnyak commented
Поднимаю до 10

2022-05-17 20:38 UTC, closed without merging