Кошкелян Тигран Задание 2
sopilnyak/dotnet-course pull request #31
Opened 2022-05-02 02:00 UTC by TIGRAN02

2022-05-14 14:39 UTC, sokolovdenis requested changes

2022-05-14 14:39 UTC, sokolovdenis commented on 05-multithreading/Solution/RSSReader.cs
> +        Task.WhenAll(fetchTasks).Wait();
Wait при написании этой домашки запрещён :)
Нужно переписать таким образом, чтобы в каждый момент времени была максимально возможная параллельность асинхронных операций. Параллельно скачиваются RSS ленты от каждого источника (это уже сделано), по мере готовности каждой ленты для неё запускается параллельное скачивание статей.

2022-05-14 14:39 UTC, sokolovdenis commented on 05-multithreading/Solution/RSSReader.cs
> +    private static IEnumerable<ArticleInfo> FilterOutProcessed(IEnumerable<ArticleInfo> all,
Функционал добавлению и проверке статей следует вынести в отдельный класс. См. Single Responsibility Principle

2022-05-14 20:05 UTC, TIGRAN02 commented on 05-multithreading/Solution/RSSReader.cs
> +        Task.WhenAll(fetchTasks).Wait();
Оставил ровно 1 Wait, который просто ждет завершения всей задачи (чтение rss ссылок + их парсинг + скачивание статей + сохранение их на диск и в список обработанных), чтобы периодичность правильно работала (начинаем следующую итерацию через n минут после _завершения_ предыдущей)

2022-05-14 20:06 UTC, TIGRAN02 commented on 05-multithreading/Solution/RSSReader.cs
> +    private static IEnumerable<ArticleInfo> FilterOutProcessed(IEnumerable<ArticleInfo> all,
Вынес это и не только)

2022-05-15 15:12 UTC, sokolovdenis commented on 05-multithreading/Solution/FileManager.cs
> +        lock (_processedFilepath)
Здесь получается узкое место в системе, если источников и статей будет много.

2022-05-15 15:13 UTC, sokolovdenis commented on 05-multithreading/Solution/RssReader.cs
> +                .ContinueWith(task =>
Синтаксис async await как раз и был придуман для того, чтобы не городить подобные лестничные сложно-читаемые конструкции в коде.

2022-05-15 15:14 UTC, sokolovdenis commented
предварительно 4 балла из 5

2022-05-15 16:01 UTC, TIGRAN02 commented on 05-multithreading/Solution/FileManager.cs
> +        lock (_processedFilepath)
Теперь лок берется 1 раз на RSS ленту, поскольку их мало, то узкого места не будет. Можно было бы еще вообще 1 раз сохранять на итерацию, тогда лок был бы вообще не нужен, но поскольку список новых статей мы узнаём только после парсинга XML, который происходит в разных потоках, то у нас все равно был бы лок на аггрегирующую структуру (в которой в конце был бы записан полный список новых статей), и это бы не помогло

2022-05-15 16:02 UTC, TIGRAN02 commented on 05-multithreading/Solution/RssReader.cs
> +                .ContinueWith(task =>
Спасибо! Исправил

2022-05-16 18:14 UTC, sokolovdenis commented
5 баллов из 5

2022-05-18 18:29 UTC, closed without merging