Файзуллин Музаффар Задание 2
sopilnyak/dotnet-course pull request #32
Opened 2022-05-02 23:49 UTC by fayzullin

2022-05-14 15:25 UTC, sokolovdenis requested changes

2022-05-14 15:25 UTC, sokolovdenis commented on 05-multithreading/Program.cs
> +        var rssFeedLinks = ReadRssFeedLinks();
Нужно сделать чуть более параллельно всё.
То есть, не ждать, когда загрузятся все RSS ленты, и только потом этого переходить к следующему этапу. А по ходу загрузки каждой ленты её парсить и в параллель запускать загрузку всех необработанных статей из неё.

2022-05-14 15:25 UTC, sokolovdenis commented on 05-multithreading/Program.cs
> +public static class EventLoop
Ради улучшения читаемости кода нужно положить каждый класс в отдельный файл.

2022-05-15 14:58 UTC, sokolovdenis commented
предварительно 2 балла из 5

2022-05-23 22:21 UTC, fayzullin commented on 05-multithreading/Program.cs
> +        var rssFeedLinks = ReadRssFeedLinks();
Каждая лента начинает обрабатываться независимо после загрузки из файла.

2022-05-26 18:27 UTC, sokolovdenis commented on 05-multithreading/EventLoop.cs
> +    private static List<string> ReadLinesFromFile(string path)
см. существующий метод File.ReadAllLinesAsync

2022-05-26 18:28 UTC, sokolovdenis commented on 05-multithreading/EventLoop.cs
> +            _stats.FeedsProcessed++;
это не атомарная операция, см. класс Interlocked

2022-05-26 18:30 UTC, sokolovdenis commented on 05-multithreading/Program.cs
> +        var rssFeedLinks = ReadRssFeedLinks();
Судя по коду - сейчас последовательно проходимся по каждому RSS фиду, а в рамках фида - последовательно по каждой статье внутри него. А нужно и фиды обрабатывать параллельно, и в рамках каждого из них статьи грузить параллельно.

2022-05-27 09:02 UTC, sokolovdenis commented
5 из 5 посла правок

2022-05-27 09:02 UTC, closed without merging