Файзуллин Музаффар Задание 3
sopilnyak/dotnet-course pull request #34
Opened 2022-05-09 17:09 UTC by fayzullin

2022-05-15 19:11 UTC, sopilnyak requested changes
Предварительная оценка (без исправлений): 8 баллов из 10, с учетом дедлайна - 4 баллов из 5.

2022-05-15 19:11 UTC, sopilnyak commented on 06-testing/HW3/BatchIterator.Tests.cs
> +    [TestCase(new string[] { "1", "2", "3", "4", "5" }, 2, true)]
Здесь тоже можно `new[]`

2022-05-15 19:11 UTC, sopilnyak commented on 06-testing/HW3/BatchIterator.Tests.cs
> +    [TestCase(new[] { 1, 2, 3, 4 }, 2, true)]
Нужно еще добавить тесты на невалидный batchSize (например, 0 или < 0). Должно кидаться адекватное исключение.

2022-05-15 19:11 UTC, sopilnyak commented on 06-testing/HW3/Document.cs
> +            throw new ArgumentException("trainSize " + trainSize + " must between 0 and 1");
Лучше использовать string interpolation + вместо строки "trainSize" указывать nameof(trainSize). Это защищает от случая, когда переименовали переменную и забыли переименовать название аргумента.

2022-05-15 19:11 UTC, sopilnyak commented on 06-testing/HW3/Document.cs
> +        var shuffledDocuments = sortedDocuments.OrderBy(_ => randomGenerator.Next()).ToList();
Можно этот OrderBy объединить с предыдущими (будет еще один ThenBy)

2022-05-18 06:17 UTC, fayzullin commented on 06-testing/HW3/Document.cs
> +        var shuffledDocuments = sortedDocuments.OrderBy(_ => randomGenerator.Next()).ToList();
На мой взгляд - это ухудшит читаемость кода. Уже сейчас с ходу непонятно, для чего нужно сортировать, чтобы потом пошафлить, а если объединить эти два действия, то будет еще более непонятно.

2022-05-18 06:43 UTC, fayzullin commented on 06-testing/HW3/BatchIterator.cs
> +    public BatchIterator(IEnumerable<T> data, int batchSize, bool dropLast = true)
Если я захочу исследовать зависимость точности модели от размера батча и количества батчей в трейн/тест выборке, то я могу использовать dropLast, особенно если размер батча не сильно больше, чем размер всего датасета, то это существенно

2022-05-18 06:44 UTC, fayzullin commented on 06-testing/HW3/BatchIterator.cs
> +    public BatchIterator(IEnumerable<T> data, int batchSize, bool dropLast = true)
Замечание : Н-р для питоновских DataLoader-ов - это стандартная практика

2022-05-18 07:36 UTC, fayzullin commented on 06-testing/HW3/BatchIterator.cs
> +            yield return _data.Skip(start).Take(_batchSize);
Поправил

2022-05-18 07:37 UTC, fayzullin commented
Тривиальные исправления закрыл сам без отбивки о том, что пофиксил

2022-05-22 18:06 UTC, sopilnyak commented on 06-testing/HW3/BatchIterator.cs
> +        while ((start + _batchSize < _data.Count()) ^ (!_dropLast && start < _data.Count()))
.Count() в общем случае (если _data не реализует IList) будет работать за линию, так что есть смысл заранее сохранить значение

2022-05-22 18:06 UTC, sopilnyak commented on 06-testing/HW3/Document.cs
> +        var shuffledDocuments = sortedDocuments.OrderBy(_ => randomGenerator.Next()).ToList();
Согласна

2022-05-22 18:07 UTC, sopilnyak commented
Поднимаю до 5 из 5.

2022-05-22 18:07 UTC, closed without merging