Малхасян Арсен Homework1
sopilnyak/dotnet-course pull request #7
Opened 2022-03-10 19:57 UTC by ArsenMalkh

2022-05-02 15:52 UTC, sopilnyak requested changes
Интересный выбор алгоритма сортировки, но задание скорее про архитектуру, чем про алгоритмы. К тому же, не выполнено требование про выбор механизма логирования (в консоль или на диск).
Предварительная оценка (без исправлений): 5 баллов из 10.

2022-05-02 15:52 UTC, sopilnyak commented on 02-oop/Program.cs
> +            String.Format("{0:00}:{1:00}:{2:00}.{3:00}", ts.Hours, ts.Minutes, ts.Seconds, ts.Milliseconds / 10);
В современном C# можно написать вот так:
`string elapsedTime = $"{ts.Hours:00}:{ts.Minutes:00}:{ts.Seconds:00}.{ts.Milliseconds / 10:00}";`

2022-05-02 15:52 UTC, sopilnyak commented on 02-oop/Program.cs
> +        b = t;
Всю эту конструкцию можно заменить:
`(a, b) = (b, a);`

2022-05-02 15:52 UTC, sopilnyak commented on 02-oop/Program.cs
> +    public static void StartLog<T>(T[] items, string algo_name)
В задании нужно было еще сделать возможность выбора, куда писать лог: в консоль или в файл.

2022-05-02 15:52 UTC, sopilnyak commented on 02-oop/Program.cs
> +public class SortAlgorithms
Очень неудачная архитектура, когда в одном классе лежат все способы сортировки. Такая архитектура очень усложняет добавление новых алгоритмов + класс разрастается с каждой реализацией.
Каждый алгоритм сортировки должен быть в своем классе, реализующем некоторый интерфейс ISorter. Также должен быть класс, который решает, какой метод сортировки выбрать.

2022-05-02 15:52 UTC, sopilnyak commented on 02-oop/Program.cs
> +        T[] temp = new T[length];
Здесь тоже можно писать var, чтобы не дублировать тип

2022-05-02 15:52 UTC, sopilnyak commented on 02-oop/Program.cs
> +    private static int[] generateArray(int count)
По кодстайлу все методы (даже приватные) пишутся с большой буквы

2022-05-02 15:52 UTC, sopilnyak commented on 02-oop/Program.cs
> +                    j = j - increment;
В C# есть оператор -=

2022-05-02 15:52 UTC, sopilnyak commented on 02-oop/Program.cs
> +        int i, j, increment;
А зачем эти переменные в начале объявлять?

2022-05-02 15:52 UTC, sopilnyak commented on 02-oop/Program.cs
> +public class Log
Принято разносить каждый класс в отдельный файл, а в Program.cs держать только class Program

2022-05-06 21:35 UTC, ArsenMalkh commented on 02-oop/Program.cs
> +            String.Format("{0:00}:{1:00}:{2:00}.{3:00}", ts.Hours, ts.Minutes, ts.Seconds, ts.Milliseconds / 10);
исправил

2022-05-06 21:35 UTC, ArsenMalkh commented on 02-oop/Program.cs
> +        b = t;
исправил

2022-05-06 21:35 UTC, ArsenMalkh commented on 02-oop/Program.cs
> +    public static void StartLog<T>(T[] items, string algo_name)
исправил

2022-05-06 21:35 UTC, ArsenMalkh commented on 02-oop/Program.cs
> +public class SortAlgorithms
исправил

2022-05-06 21:35 UTC, ArsenMalkh commented on 02-oop/Program.cs
> +        T[] temp = new T[length];
исправил

2022-05-06 21:35 UTC, ArsenMalkh commented on 02-oop/Program.cs
> +    private static int[] generateArray(int count)
исправил

2022-05-06 21:35 UTC, ArsenMalkh commented on 02-oop/Program.cs
> +                    j = j - increment;
исправил

2022-05-06 21:35 UTC, ArsenMalkh commented on 02-oop/Program.cs
> +        int i, j, increment;
исправил

2022-05-06 21:35 UTC, ArsenMalkh commented on 02-oop/Program.cs
> +public class Log
исправил

2022-05-06 21:36 UTC, ArsenMalkh commented
исправил все замечания

2022-05-07 10:35 UTC, ArsenMalkh commented
все, добавил

2022-05-11 20:23 UTC, sopilnyak commented on 02-oop/Program.cs
> +            String.Format("{0:00}:{1:00}:{2:00}.{3:00}", ts.Hours, ts.Minutes, ts.Seconds, ts.Milliseconds / 10);
А строкой ниже опять склеенные строки (кстати изначально нормально же было)
`string line1 = "отсортировано за " + elapsedTime +" времени" + "\r\n\n";`

2022-05-11 20:52 UTC, sopilnyak requested changes
Оценка с исправлениями: 8 баллов из 10. Надо исправить архитектуру логирования, чтобы было больше.

2022-05-11 20:52 UTC, sopilnyak commented on 02-oop/Log.cs
> +    public class Log
Нехорошо привязывать реализации логгера к конкретному кейсу его использования (в твоем случае он знает почему-то про сортировку, про таймер и про 2 варианта записи - в файл и в консоль). Конструкция `if (is_infile) ... else ...` тоже выглядит не очень, потому что затрудняет добавление новых реализаций логирования.

Могу предложить такой вариант архитектуры. Пусть у нас будет некоторый интерфейс ILogger с единственным методом `void Log(string message)`, у него будет две реализации: ConsoleLogger и FileLogger. В существующем классе `Log` (это уже даже скорее не `Log`, а что-то вроде `Timer`) пусть останутся методы StartLog и EndLog, которые пишут "получен массив..." и т.п., а также запускают таймер. Но вместо записи в консоль/в файл, они будут звать метод ILogger.Log. Также вместо флага `is_infile` лучше в `SelectSort` передавать прямо экземпляр какой-либо из реализаций ILogger.

2022-05-11 20:52 UTC, sopilnyak commented on 02-oop/Log.cs
> +                using(FileStream stream = new FileStream("logs.txt", FileMode.Append)){
Можно писать using без скобок:
`using var stream = new FileStream("logs.txt", FileMode.Append)`
Тогда стрим закроется как только переменная stream выйдет из области видимости.

2022-05-11 20:52 UTC, sopilnyak commented on 02-oop/Log.cs
> +                    stream.Write(array1, 0, array1.Length);
Для записи строки лучше использовать StreamWriter:
```
using var streamWriter = new StreamWriter(stream);
streamWriter.WriteLine(line1);
```

2022-05-14 11:40 UTC, ArsenMalkh commented on 02-oop/Log.cs
> +    public class Log
исправил

2022-05-14 11:41 UTC, ArsenMalkh commented on 02-oop/Log.cs
> +                using(FileStream stream = new FileStream("logs.txt", FileMode.Append)){
исправил

2022-05-14 11:41 UTC, ArsenMalkh commented on 02-oop/Log.cs
> +                    stream.Write(array1, 0, array1.Length);
исправил

2022-05-14 11:41 UTC, ArsenMalkh commented
все исправлено

2022-05-17 20:45 UTC, sopilnyak commented on 02-oop/Log.cs
> +    public class Log
Теперь ок

2022-05-17 20:47 UTC, sopilnyak commented on 02-oop/Log.cs
> +                using(FileStream stream = new FileStream("logs.txt", FileMode.Append)){
В FileLogger.Log осталось, ну да ладно

2022-05-17 20:47 UTC, sopilnyak commented
Поднимаю до 10

2022-05-17 20:47 UTC, closed without merging